name: Workflow Manual com inputs/tags/environment
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        required: false
        default: 'prd'
        type: choice
        options:
          - prd
          - hml
          - dev
      docker-server:
        description: Selecione o servidor docker
        required: true
        type: choice
        options:
        - ubuntu-latest
        - self-host
        - oracle-04
        - oracle-01

jobs:
  log-the-inputs:
    runs-on: [self-hosted, "${{ inputs.docker-server }}"]
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "docker-server: ${{ inputs.docker-server }}"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
